### ISSUE TITLE
Upgrade to latest version of Gradle

### ISSUE THREAD

**Issue by tkgregory** [JustinPihony/gradle-aws-plugin-reboot#4]
This project is built using Gradle 4.6 from Feb 28, 2018. It should be upgraded to Gradle 6.7.1+ to make use of the latest Gradle features.

So far I've spotted that the `findbugs` plugin no longer exists in newer Gradle versions.

Are there any other known issues?

**Comment by JustinPihony** [comment]
I just pushed to 7.1.1
